### ISSUE TITLE
Authorization problem using locate parameter

### ISSUE THREAD

**Issue by aborruso** [decklin/curlicue#3]
Hi,
if I use this command 
```
curlicue -f credentials 'https://stream.twitter.com/1.1/statuses/filter.json?track=pizza'
```

I have the related streams results.

If I had location
```
curlicue -f credentials 'https://stream.twitter.com/1.1/statuses/filter.json?track=pizza&locations=-180,-90,180,90'
```
I have "Unauthorized", HTTP ERROR: 401 error.

What's wrong in my procedure?

Thank you

**Comment by decklin** [comment]
I'm on a phone right now so I can't verify this, but I believe the problem is that the commas in your `locations` parameter are not URL-encoded (`%2C`). What's happening is that the signature is calculated on the literal value you passed, but the server expects a signature on the properly encoded URL.

**Comment by aborruso** [comment]
@decklin it works, I'm stupid :)

Thank you very much
